MODULE DEBUGMOD
IMPLICIT NONE
CONTAINS
	SUBROUTINE DEBUGCP(DEBUG,MSG,CODE)
		LOGICAL :: DEBUG
		CHARACTER(*) :: MSG
		INTEGER*4 :: CODE
		IF (DEBUG) THEN
			PRINT*,MSG
			PRINT*,CODE
		END IF
	END SUBROUTINE
END MODULE

PROGRAM DEBUGTEST
USE DEBUGMOD
	REAL*4 :: X
	integer*4 :: ii,NN
	NN= 10
	do ii=1,NN
		X = RAND(0)
		print*,X
		CALL DEBUGCP(X>0.5,"TOO BIG",0)
	end do
END PROGRAM
